# Урок 4

# Матрицы и матричные операции. Часть 2

## Практическое задание

In [1]:
import numpy as np

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a) $A_1 =$

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$


$ detA_1 = sin^2x + cos^2x = 1 $

In [2]:
x = np.pi
cos_x = np.cos(x)
a_1 = np.array([[np.sin(x), -cos_x], [cos_x, np.sin(x)]])
print(f'Определитель:\n{np.linalg.det(a_1):.0f}')

Определитель:
1



   б) $A_2 =$
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    


$A_2$ диагональная матрица
$ det A_2 = 4 * 5* 9 =180$

In [3]:
a_2 = np.array([[4,2,3], [0,5,1],[0,0,9]])
print(f'Определитель:\n{np.linalg.det(a_2):.0f}')

Определитель:
180


   в) $A_3 =$

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

 - У матрицы $ A_3$ линейно-зависимые столбцы, определитель должен быть равен 0
$ 1*(5*9 - 6*8) - 2*(4*9-6*7) + 3*(4*8-7*5) = -3-2*(-6)+3*(-3)= -3 +12-9 = 0$

In [4]:
1*(5*9 - 6*8) - 2*(4*9-6*7) + 3*(4*8-7*5)

0

In [5]:
a_3 = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(f'Определитель:\n{np.linalg.det(a_3):.0f}')

Определитель:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$ ;
Для двух квадратных матриц одинакового размера $det(AB)=detA\cdot detB.$ => $det(A^{2}) = detA \cdot detA = 16 $
    
   б) $det(A^{T})$; Определитель транспонированной матрицы равен определителю исходной => $det(A^{T})=4$
    
   в) $det(2A)$. Умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число. =><br>
               $ det(2A) = 4 \cdot (2  $ в степени количества строк матрицы)

In [6]:
b = np.array([[-1, -4, 0, -2], [0, 1, 5, 4], [3, 1, 1, 0], [-1, 0, 2, 2]])
print(f'Матрица B =\n{b}')
print(f'Определитель матрицы B = {np.linalg.det(b):.0f}')
print(f' - 12 * (2 в степени количества строк матрицы) = {np.linalg.det(b) * (2**4)}')
print(f'Определитель  посредством функции библиотеи numpy: ={np.linalg.det(2*b):.0f}')

Матрица B =
[[-1 -4  0 -2]
 [ 0  1  5  4]
 [ 3  1  1  0]
 [-1  0  2  2]]
Определитель матрицы B = -12
 - 12 * (2 в степени количества строк матрицы) = -192.0
Определитель  посредством функции библиотеи numpy: =-192


__3.__  Доказать, что матрица
$$ С =\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.
 - в вырожденной матрице существует как минимум две строки (или два столбца), один из которых можно выразить через другой.
 В нашем случае строку№2 можно выразить через строку№1 * на скаляр = (- 2)  
 - ее определитель равен нулю:

In [7]:
print(f'Определитель С ={-2*((-14*13) -(7*6)) - 7*(4*13- (-3*6)) + (-3*(4*7 - (-14*-3)))}')
с = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель С ={np.linalg.det(с):.0f}')

Определитель С =0
Определитель С =0


__4.__ Найти ранг матрицы:

а) $D_1 = \begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

- вектор-строка 3 = вектор-строка1 + вектор-строка 2 => ранг матрицы не равен 3
- определитель минора второго порядка не равен 0 => матрица имеет ранг 2

In [8]:
d_1 = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(d_1)

print(f'Ранг матрицы D_1: {r}')

Ранг матрицы D_1: 2




   б) $D_2= \begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

- третью строку можно исключить, так как она может быть получена сложением первых двух
- определитель минора третьего порядка не равен 0 (равен 6) => матрица имеет ранг 3

In [9]:
d_2 = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r_2 = np.linalg.matrix_rank(d_2)

print(f'Ранг матрицы D_2: {r_2}')

Ранг матрицы D_2: 3
